name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -uses: actions/setup-node@v3
      with:
        node-version: v24.11.1
        cache: npm
      -run: yarn install

      -name: Build
      run: yarn Build

      -name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.TOKEN}}
        publish_dir: dist